### ISSUE TITLE
Separate library or not?

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/wac-allow#1]
I wanted to have your opinion whether we should have `WAC-Allow` parsing (and possible generation) in a separate library or not.

On the one hand, it doesn't satisfy the "a least 3 separate uses" criterion, but on the other hand, it does satisfy the "obvious enough to reuse" criterion.

**Comment by dan-f** [comment]
I think you should go ahead with it. It seems like a relatively well-defined piece of logic without IO, so I say go for it!

**Comment by RubenVerborgh** [comment]
Library it is: https://www.npmjs.com/package/wac-allow
